# Generated by Django 5.0.3 on 2024-03-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeproject',
            options={'ordering': ('status',), 'verbose_name': 'Employee Project', 'verbose_name_plural': 'Employee Projects'},
        ),
    ]
