# Generated by Django 5.0.3 on 2024-03-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='project_status',
            field=models.CharField(blank=True, choices=[('Web DEvelopment', 'Devops Engineer'), ('UX / UI Designing', 'Mobile App Development')], max_length=50, null=True),
        ),
    ]
