# Generated by Django 5.0.3 on 2024-03-18 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_project_status'),
        ('project_manager', '0009_remove_project_project_status_alter_project_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_manager.project'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='project_status',
            field=models.CharField(blank=True, choices=[('UX / UI Designing', 'Mobile App Development'), ('Web DEvelopment', 'Devops Engineer')], max_length=50, null=True),
        ),
    ]
