# Generated by Django 5.0.3 on 2024-03-18 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeeproject'),
        ),
        migrations.AddField(
            model_name='employeeproject',
            name='assign_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeproject',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeproject',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeproject',
            name='project_status',
            field=models.CharField(blank=True, choices=[('to_do', 'To do'), ('on_progress', 'On progress'), ('paused', 'Paused'), ('completed', 'Completed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='project_status',
            field=models.CharField(blank=True, choices=[('web_development', 'Web Development'), ('mobile_app_development', 'Mobile App Development'), ('devops_engineer', 'Devops Engineer'), ('ui_ux_designing', 'UX / UI Designing')], max_length=50, null=True),
        ),
    ]
