# Generated by Django 5.0.3 on 2024-03-18 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_employee_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('name',), 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_project',
        ),
        migrations.RemoveField(
            model_name='employeeproject',
            name='project',
        ),
        migrations.AddField(
            model_name='employeeproject',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='project_status',
            field=models.CharField(blank=True, choices=[('ui_ux_designing', 'UX / UI Designing'), ('devops_engineer', 'Devops Engineer'), ('mobile_app_development', 'Mobile App Development'), ('web_development', 'Web Development')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='priority',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('low', 'Low'), ('high', 'High'), ('normal', 'Normal')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='project_status',
            field=models.CharField(blank=True, choices=[('on_progress', 'On progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('to_do', 'To do')], max_length=50, null=True),
        ),
    ]
