# Generated by Django 5.0.3 on 2024-03-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employeeproject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='project_status',
            field=models.CharField(blank=True, choices=[('mobile_app_development', 'Mobile App Development'), ('web_development', 'Web Development'), ('ui_ux_designing', 'UX / UI Designing'), ('devops_engineer', 'Devops Engineer')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='priority',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('normal', 'Normal'), ('high', 'High'), ('low', 'Low')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='project_status',
            field=models.CharField(blank=True, choices=[('on_progress', 'On progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('to_do', 'To do')], null=True),
        ),
    ]
