# Generated by Django 5.0.3 on 2024-03-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_employee_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='project_status',
            field=models.CharField(blank=True, choices=[('mobile_app_development', 'Mobile App Development'), ('devops_engineer', 'Devops Engineer'), ('ui_ux_designing', 'UX / UI Designing'), ('web_development', 'Web Development')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='project_status',
            field=models.CharField(blank=True, choices=[('on_progress', 'On progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('to_do', 'To do')], null=True),
        ),
    ]
