# Generated by Django 5.0.3 on 2024-03-18 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_employee_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='project_status',
            field=models.CharField(blank=True, choices=[('devops_engineer', 'Devops Engineer'), ('web_development', 'Web Development'), ('mobile_app_development', 'Mobile App Development'), ('ui_ux_designing', 'UX / UI Designing')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('normal', 'Normal'), ('urgent', 'Urgent'), ('low', 'Low')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='project_status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('paused', 'Paused'), ('on_progress', 'On progress'), ('to_do', 'To do')], null=True),
        ),
    ]
