# Generated by Django 5.0.3 on 2024-03-19 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_employee_user_id_alter_employee_designation_and_more'),
        ('project_manager', '0019_alter_project_priority_alter_project_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_manager.project'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('mobile_app_development', 'Mobile App Development'), ('web_development', 'Web Development'), ('ui_ux_designing', 'UX / UI Designing'), ('devops_engineer', 'Devops Engineer')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='priority',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('normal', 'Normal'), ('high', 'High'), ('low', 'Low')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='project_status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('on_progress', 'On progress'), ('to_do', 'To do'), ('paused', 'Paused')], null=True),
        ),
    ]
