# Generated by Django 5.0.3 on 2024-03-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_remove_employee_user_id_employee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('ui_ux_designing', 'UX / UI Designing'), ('devops_engineer', 'Devops Engineer'), ('mobile_app_development', 'Mobile App Development'), ('web_development', 'Web Development')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='priority',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('normal', 'Normal'), ('low', 'Low'), ('high', 'High')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='project_status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('paused', 'Paused'), ('to_do', 'To do'), ('on_progress', 'On progress')], null=True),
        ),
    ]
