# Generated by Django 5.0.3 on 2024-03-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_employee_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_project',
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('ui_ux_designing', 'UX / UI Designing'), ('web_development', 'Web Development'), ('devops_engineer', 'Devops Engineer'), ('mobile_app_development', 'Mobile App Development')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='priority',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('low', 'Low'), ('high', 'High')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='project_status',
            field=models.CharField(blank=True, choices=[('paused', 'Paused'), ('on_progress', 'On progress'), ('to_do', 'To do'), ('completed', 'Completed')], null=True),
        ),
    ]
