# Generated by Django 5.0.3 on 2024-03-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_alter_employee_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('mobile_app_development', 'Mobile App Development'), ('ui_ux_designing', 'UX / UI Designing'), ('devops_engineer', 'Devops Engineer'), ('web_development', 'Web Development')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='project_status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('on_progress', 'On progress'), ('to_do', 'To do'), ('paused', 'Paused')], null=True),
        ),
    ]
