# Generated by Django 5.0.3 on 2024-03-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0030_alter_employee_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('mobile_app_development', 'Mobile App Development'), ('devops_engineer', 'Devops Engineer'), ('web_development', 'Web Development'), ('ui_ux_designing', 'UX / UI Designing')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('low', 'Low'), ('urgent', 'Urgent'), ('normal', 'Normal')], null=True),
        ),
    ]
