# Generated by Django 5.0.3 on 2024-03-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0031_alter_employee_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('web_development', 'Web Development'), ('mobile_app_development', 'Mobile App Development'), ('ui_ux_designing', 'UX / UI Designing'), ('devops_engineer', 'Devops Engineer')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='priority',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('low', 'Low'), ('high', 'High')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='project_status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('paused', 'Paused'), ('over_due', 'Overdue'), ('on_progress', 'On progress'), ('to_do', 'To do')], null=True),
        ),
    ]
