# Generated by Django 5.0.3 on 2024-03-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0032_alter_employee_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeproject',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('mobile_app_development', 'Mobile App Development'), ('ui_ux_designing', 'UX / UI Designing'), ('web_development', 'Web Development'), ('devops_engineer', 'Devops Engineer')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='priority',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('high', 'High'), ('low', 'Low')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='project_status',
            field=models.CharField(blank=True, choices=[('over_due', 'Overdue'), ('to_do', 'To do'), ('completed', 'Completed'), ('paused', 'Paused'), ('on_progress', 'On progress')], null=True),
        ),
    ]
