# Generated by Django 5.0.3 on 2024-03-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0033_employeeproject_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('web_development', 'Web Development'), ('devops_engineer', 'Devops Engineer'), ('mobile_app_development', 'Mobile App Development'), ('ui_ux_designing', 'UX / UI Designing')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], null=True),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='project_status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('to_do', 'To do'), ('over_due', 'Overdue'), ('paused', 'Paused'), ('on_progress', 'On progress')], null=True),
        ),
    ]
