# Generated by Django 5.0.3 on 2024-03-16 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=156)),
                ('team_lead', models.CharField(max_length=156)),
            ],
            options={
                'verbose_name': 'Deadline project',
                'verbose_name_plural': 'Deadline Projects',
                'db_table': 'project_manager_deadline_project',
                'ordering': ('project_name',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'project_manager_employees',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=156)),
            ],
            options={
                'verbose_name': 'Priority',
                'verbose_name_plural': 'Priorities',
                'db_table': 'project_manager_priority',
                'ordering': ('priority',),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=156)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'db_table': 'project_manager_status',
                'ordering': ('status',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=256)),
                ('assigned_date', models.DateField()),
                ('submission_date', models.DateField()),
                ('description', models.TextField()),
                ('team_lead', models.CharField(max_length=256)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.employee')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.priority')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.status')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'project_manager_project',
                'ordering': ('project_name',),
            },
        ),
    ]
