# Generated by Django 5.0.3 on 2024-03-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0005_remove_project_employee_name_remove_project_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('Normal', 'Low'), ('Urgent', 'High')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('On progress', 'Completed'), ('To do', 'Paused')], max_length=50, null=True),
        ),
    ]
