# Generated by Django 5.0.3 on 2024-03-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0007_alter_project_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('Urgent', 'Urgent'), ('Normal', 'Normal'), ('High', 'Low'), ('High', 'High')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('To do', 'Paused'), ('On progress', 'Completed')], max_length=50, null=True),
        ),
    ]
