# Generated by Django 5.0.3 on 2024-03-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0008_alter_project_priority_alter_project_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_status',
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('High', 'High'), ('High', 'Low'), ('Urgent', 'Urgent')], max_length=50, null=True),
        ),
    ]
