# Generated by Django 5.0.3 on 2024-03-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0009_remove_project_project_status_alter_project_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('paused', 'Paused'), ('completed', 'Completed'), ('on_progress', 'On progress'), ('to_do', 'To do')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], max_length=50, null=True),
        ),
    ]
