# Generated by Django 5.0.3 on 2024-03-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0010_project_project_status_alter_project_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('to_do', 'To do'), ('on_progress', 'On progress'), ('paused', 'Paused'), ('completed', 'Completed')], max_length=50, null=True),
        ),
    ]
