# Generated by Django 5.0.3 on 2024-03-19 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0022_alter_project_priority_alter_project_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanger',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('urgent', 'Urgent'), ('normal', 'Normal'), ('low', 'Low')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('to_do', 'To do'), ('paused', 'Paused'), ('on_progress', 'On progress'), ('completed', 'Completed')], null=True),
        ),
    ]
