# Generated by Django 5.0.3 on 2024-03-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_alter_employee_designation_and_more'),
        ('project_manager', '0023_projectmanger_user_alter_project_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employee',
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('paused', 'Paused'), ('on_progress', 'On progress'), ('to_do', 'To do'), ('completed', 'Completed')], null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, to='employee.employee'),
        ),
    ]
