# Generated by Django 5.0.3 on 2024-03-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0025_alter_project_priority_alter_project_project_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deadline',
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low'), ('urgent', 'Urgent')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('paused', 'Paused'), ('completed', 'Completed'), ('on_progress', 'On progress'), ('to_do', 'To do'), ('over_due', 'Overdue')], null=True),
        ),
    ]
