# Generated by Django 5.0.3 on 2024-03-20 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0027_remove_project_employee_project_team_lead_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectManger',
            new_name='ProjectManager',
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('high', 'High'), ('urgent', 'Urgent'), ('normal', 'Normal')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('over_due', 'Overdue'), ('paused', 'Paused'), ('on_progress', 'On progress'), ('to_do', 'To do')], null=True),
        ),
    ]
