# Generated by Django 5.0.3 on 2024-03-20 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0028_rename_projectmanger_projectmanager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmanager',
            old_name='project',
            new_name='project1',
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_manager.projectmanager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('to_do', 'To do'), ('paused', 'Paused'), ('over_due', 'Overdue'), ('on_progress', 'On progress')], null=True),
        ),
    ]
