# Generated by Django 5.0.3 on 2024-03-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0029_rename_project_projectmanager_project1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='manager',
            new_name='project_manager',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('on_progress', 'On progress'), ('over_due', 'Overdue'), ('to_do', 'To do'), ('paused', 'Paused')], null=True),
        ),
    ]
