# Generated by Django 5.0.3 on 2024-03-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0030_rename_manager_project_project_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmanager',
            old_name='project1',
            new_name='project_manager_project',
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('high', 'High'), ('low', 'Low'), ('urgent', 'Urgent')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('paused', 'Paused'), ('over_due', 'Overdue'), ('on_progress', 'On progress'), ('to_do', 'To do')], null=True),
        ),
    ]
