# Generated by Django 5.0.3 on 2024-03-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0031_rename_project1_projectmanager_project_manager_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('urgent', 'Urgent'), ('normal', 'Normal'), ('low', 'Low')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('paused', 'Paused'), ('over_due', 'Overdue'), ('completed', 'Completed'), ('on_progress', 'On progress'), ('to_do', 'To do')], null=True),
        ),
    ]
