# Generated by Django 5.0.3 on 2024-03-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0037_alter_project_priority_alter_project_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('to_do', 'To do'), ('over_due', 'Overdue'), ('paused', 'Paused'), ('on_progress', 'On progress')], null=True),
        ),
    ]
