# Generated by Django 5.0.3 on 2024-03-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0038_alter_project_priority_alter_project_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low'), ('urgent', 'Urgent')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('over_due', 'Overdue'), ('to_do', 'To do'), ('on_progress', 'On progress'), ('completed', 'Completed'), ('paused', 'Paused')], null=True),
        ),
    ]
