# Generated by Django 5.0.3 on 2024-04-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0040_alter_project_priority_alter_project_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='pofile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('high', 'High'), ('low', 'Low')], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('on_progress', 'On progress'), ('to_do', 'To do'), ('over_due', 'Overdue'), ('completed', 'Completed'), ('paused', 'Paused')], null=True),
        ),
    ]
